#-------------------------------
# General Site Settings
title: Robin Prospect
logo: /images/logo-simple.jpg
description: "Facilitator ¦ Organisational development ¦ Diversity, equity and inclusion"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robinprospect.com" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Robin Prospect
  image: '/images/logo-simple.jpg'
  avatar: '/images/logo-simple.jpg'
  description: "Facilitator ¦ Organisational development ¦ Diversity, equity and inclusion"


#-------------------------------
# Contact links

# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
contact:
#- {name: "Twitter", icon: "ion-logo-twitter", link: "https://twitter.com"}
#- {name: "Facebook", icon: "ion-logo-facebook", link: "https://www.facebook.com/groups/645681219333097"}
- {name: "LinkedIn", icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/robin-prospect-0b53a41a0?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BXeOa%2FAZhSdeLO0YHIRqyPQ%3D%3D"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: change-it-up # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp-description: Subscribe to our newsletter and we’ll send you the emails of latest posts.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  # This does not work with GitHub pages
  # - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

#-------------------------------
# Local dev settings
port: 3000
host: 0.0.0.0
livereload: true
